[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#c7af85"
backgroundColor = "#09131f"
secondaryBackgroundColor = "#101d2b"
textColor = "#eee5d4"
font = "sans serif"
headingFont = "serif"
