[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#c7d9d2"
backgroundColor = "#0b1626"
secondaryBackgroundColor = "#121f31"
textColor = "#e7ddc9"
font = "sans serif"
headingFont = "serif"
